### ISSUE TITLE
kernel size of window_size * n (sequence length)

### ISSUE THREAD

**Issue by cgebe** [XAIseries/XCM#1]
The implementation of the XCM models uses convolutions with `kernel_size = int(window_size * n)`, e.g.:

`a = Conv2D(filters=int(filters_num), kernel_size=(int(window_size*n), 1), strides=(1, 1), padding='same', input_shape=(n, k, 1), name='2D')(input_layer)`

with `n` being input_shape[0] - the sequence length of the time series. Is this intended or am i incorrect about the input shape being [sequence_length, features]?

The paper states no such multiplication, could you please give more information on that?

**Comment by cgebe** [comment]
I double checked the input and came to the conclusion that:

```
n = number of observable variables
k = sequence length
```

That was a bit confusing in regard to the paper (D & T).

**Comment by XAIseries** [comment]
`n` corresponds to the time series length (input_shape[0] - T in the paper) and `k` to the number of observed variables (input_shape[1] - D in the paper).
`window_size` is expressed as a percentage of the total size of the MTS, therefore the size of the window used as `kernel_size` is `window_size*n`.

**Comment by cgebe** [comment]
Thank you for the answer. In the paper, the following paragraph can be found:

In parallel, XCM extracts information relative to time with 1D convolution filters
(lower red part in Figure 2). This lower part is the same as the upper part, except that
the 2D convolution filters are replaced by 1D. We set the kernel size of the 1D convolu-
tion filters to **Window Size × D**, where Window Size is the same hyperparameter as 2D
convolution filters and **D is the number of observed variables of the input data**.

Therefore, i was wondering if this matches, since the code implements the kernel with size `window_size*n` and as you state `n` being the time series length.

**Comment by XAIseries** [comment]
Yes, it corresponds to the description in the paper. By definition, conv1D is applied across the observed variables and the `kernel_size` defines the size of the filters along the time dimension.
