### ISSUE TITLE
Reproduce CAM

### ISSUE THREAD

**Issue by IKetchup** [XAIseries/XCM#2]
Hello,

First of all thanks you for your amazing paper and your code.

I am really interrested by the explenability aspect of the network. I looked in the code but I dont see any part to reproduce CAM like the figure 5 in your paper.

is there somewhere code to help me reproduce your results ?

**Comment by XAIseries** [comment]
Hello,

Thank you for your message.

Please find [here](https://github.com/jacobgil/keras-grad-cam) a link to the code that can be used for Grad-CAM.

**Comment by IKetchup** [comment]
Hello,

I am already aware of this repository. However this code only work with vgg. How and where did you add grad-CAM to your network architecture ? 

I also suppose that there is modification to do to adapt it to a customized network (https://github.com/jacobgil/keras-grad-cam/issues/23) and also other to adapt it to timeseries.

I am strugelling to adapt it. Do you have the piece of code used to generate CAM like the one in your paper?

Thanks in advance

**Comment by c3p0p3c** [comment]
@IKetchup @XAIseries Have you found a solution? I am also interested in creating a CAM for a time series CNN. I looked at the problem you cited and tried to modify the code for time series but like you I am really struggling with errors and tensor shape for the 2D conv CAM.

**Comment by IKetchup** [comment]
I managed to modify grad-CAM (based on [this] (https://github.com/albarji/keras-gradcam-demo/blob/master/keras_gradcam_demo.ipynb) cause there is problem or tensorflow version with the actual keras grad-cam) to generate CAM on conv1D using the 1D-Activation layer of XCmM. You just have to modify the line 

```
pooled_grads = tf.reduce_mean(grads, axis=(0, 1,2))
```

in 

```
pooled_grads = tf.reduce_mean(grads, axis=(0, 1))
```

The rest of the changes are basic. However for the generation of CAm from the con2D layer (2D activation) I have a problem with the size of the tensor.

I can't feed the output of my convolution into the global average pooling because the global_average_pooling1d  is waiting for a 3D tensor and i feed it a 4D tensor (because of the 2D conv). here is my full code 

````
model = XCM() 

#shape of x_test : (1,10290,11)

heatmap = make_gradcam_heatmap_2d(x_test, model, "2D_Activation", ["global_average_pooling1d", "dense"])

def make_gradcam_heatmap_2d(x_test, model, last_conv_layer_name, classifier_layer_names, top_n=0):
   

    # create a model that maps the input image to the activation  of the last conv layer
    last_conv_layer = model.get_layer(last_conv_layer_name)
    last_conv_layer_model = Model(model.inputs, last_conv_layer.output)

    # create a model that maps the activations of the last conv layer to the final class predictions
    classifier_input = Input(shape=last_conv_layer.output.shape[1:])
    x = classifier_input
    for layer_name in classifier_layer_names:
        x = model.get_layer(layer_name)(x)
    classifier_model = Model(classifier_input, x)

    #compute the gradient of the top predicted class for our input image
    with tf.GradientTape() as tape:
        # Compute activations of the last conv layer and make the tape watch it
        
        last_conv_layer_output = last_conv_layer_model(x_test)
        
        tape.watch(last_conv_layer_output)
        # Compute class predictions for single image
        
       #here is the problem
       #last_conv_layer.shape = (1, 10290, 11, 1)
       #the global_avergae_pooling_1d need a 3d tensor not 4d

        preds = classifier_model(last_conv_layer_output)[0]
        # Get output for top-k class
        idx = tf.math.top_k(preds, k=top_n+1).indices[top_n]
        target_class_channel = preds[idx]

    # This is the gradient of the target predicted class with regard to
    # the output feature map of the last conv layer
    grads = tape.gradient(target_class_channel, last_conv_layer_output)

    # This is a vector where each entry is the mean intensity of the gradient
    # over a specific feature map channel
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    # We multiply each channel in the feature map array
    # by "how important this channel is" with regard to the top predicted class
    last_conv_layer_output = last_conv_layer_output.numpy()[0]
    pooled_grads = pooled_grads.numpy()
    for i in range(pooled_grads.shape[-1]):
        last_conv_layer_output[:, :, i] *= pooled_grads[i]

    # The channel-wise mean of the resulting feature map
    # is our heatmap of class activation
    heatmap = np.mean(last_conv_layer_output, axis=-1)

    # Filter out negative values, as we want to focus on pixels that contribute positively to the class
    # Also, for visualization purposes, we will normalize the heatmap between 0 & 1
    return np.maximum(heatmap, 0) / np.max(heatmap)
````

@XAIseries how did you solve this problem to generate CAM based on the 2D conv layer ?

Thanks in advance for any help

**Comment by Corne173** [comment]
I read your paper 3 months ago and only discovered the code now. Have done a lot of work on this in the meantime. Are you open to discussions about your work? Do you have future work in the pipeline involving GradCam for multivariate timeseries models?

**Comment by LocalCascadeEnsemble** [comment]
Hello,

Thank you for your messages.
I confirm that I have also uploaded the code concerning Grad-CAM.
@Corne173 please don't hesitate to contact me by email ([kevin.fauvel@inria.fr](mailto:kevin.fauvel@inria.fr)) for discussions about future work.

Best,

**Comment by XAIseries** [comment]
Hello,

Thank you for your messages.
I confirm that I have also uploaded the code concerning Grad-CAM.
@Corne173 please don't hesitate to contact me by email ([kevin.fauvel@inria.fr](mailto:kevin.fauvel@inria.fr)) for discussions about future work.

Best,

**Comment by Corne173** [comment]
@XAIseries, thank you for uploading all your code. It makes reproducing your work much easier and it also allows others to review your implementation. I really wish more people would do this. Once again, thank you

**Comment by IKetchup** [comment]
@XAIseries Thanks for uploading your code and producing such a clean paper :)
