### ISSUE TITLE
Generate Grad-CAM

### ISSUE THREAD

**Issue by c3p0p3c** [XAIseries/XCM#3]
Hello,

Your article is very interesting for the field of network explainability.

Your network is very promising. However, I am having trouble reproducing the result you obtained for Grad-CAM.

As mentioned [here] (https://github.com/XAIseries/XCM/issues/2), I am facing a problem in generating the GradCAM "features". When creating the model for GradCAM, a 2D convolution output and a 1D convolution output are sent to a 1D global averaging layer. This generates an error because of the shape of the 2D convolution output.

How did you solve this problem?

**Comment by LocalCascadeEnsemble** [comment]
Hello,

Thank you for your message.
I confirm that I have also uploaded the code concerning Grad-CAM.

Best,

**Comment by XAIseries** [comment]
Hello,

Thank you for your message.
I confirm that I have also uploaded the code concerning Grad-CAM.

Best,
